### ISSUE TITLE
Error on package install

### ISSUE THREAD

**Issue by BenRoche** [artyom-bazyk/relatedList#1]
Hello,

i am a getting an error on install

"_You can’t change the isExposed property to ‘false’ because the component is part of a managed package._"

BR

Ben

**Comment by artyom-bazyk** [comment]
Hello @BenRoche,
Could you check on your org, if you have components with the same name as components in the Related List package?
I installed the package on several scratch orgs and did not catch errors.

**Comment by BenRoche** [comment]
You are correct, there was another component with the same Name, cheers
